import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  page: { backgroundColor: '#F8F9FC', minHeight: '100vh' as any, paddingHorizontal: 32 },
  header: { width: '100%', maxWidth: 1180, height: 100, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  logo: { width: 156, height: 71 }, links: { flexDirection: 'row', gap: 28 }, link: { color: '#667085', fontSize: 14, fontWeight: '600' },
  hero: { width: '100%', maxWidth: 1180, minHeight: 650, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  heroContent: { width: '100%', maxWidth: 540, alignItems: 'center', zIndex: 2 }, eyebrow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginBottom: 22 }, dot: { backgroundColor: '#8489C3', width: 8, height: 8, borderRadius: 99 }, eyebrowText: { color: '#667085', fontSize: 13, fontWeight: '700', letterSpacing: 0.5 },
  title: { color: '#020E56', fontSize: 62, lineHeight: 66, fontWeight: '800', letterSpacing: -2, textAlign: 'center' }, subtitle: { color: '#667085', fontSize: 17, lineHeight: 26, textAlign: 'center', maxWidth: 410, marginTop: 18, marginBottom: 30 },
  uploader: { width: '100%', minHeight: 220, borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#C9CDE4', backgroundColor: '#FFF', borderRadius: 20, alignItems: 'center', justifyContent: 'center', padding: 24, shadowColor: '#020E56', shadowOpacity: 0.06, shadowRadius: 24, shadowOffset: { width: 0, height: 12 } }, uploaderSelected: { borderStyle: 'solid', borderColor: '#8489C3', minHeight: 250 }, uploadIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#EFF0FA', alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, uploadIconText: { color: '#0E156A', fontSize: 26, fontWeight: '700' }, uploadTitle: { color: '#111827', fontSize: 15, fontWeight: '700', maxWidth: '90%' as any, textAlign: 'center' }, uploadHint: { color: '#98A2B3', fontSize: 13, marginTop: 7 }, preview: { width: '100%', height: 126, marginBottom: 12, borderRadius: 12 }, secondaryButton: { marginTop: 15, paddingVertical: 10, paddingHorizontal: 17, borderRadius: 10, backgroundColor: '#F0F1FA' }, secondaryButtonText: { color: '#0E156A', fontSize: 13, fontWeight: '700' }, message: { color: '#B42318', fontSize: 13, marginTop: 10 }, primaryButton: { backgroundColor: '#0E156A', borderRadius: 12, minHeight: 54, width: '100%', alignItems: 'center', justifyContent: 'center', marginTop: 14 }, primaryButtonText: { color: '#FFF', fontSize: 15, fontWeight: '800' }, disabledButton: { opacity: 0.45 }, apiNote: { color: '#98A2B3', fontSize: 12, marginTop: 14 },
  character: { position: 'absolute', bottom: 8, width: 160, height: 180, overflow: 'hidden', opacity: 0.72 }, characterLeft: { left: 0 }, characterRight: { right: 0 }, characterImage: { width: 420, height: 190, position: 'absolute', left: 0, top: 0 }, characterImageRight: { left: -260 },
  resultsSection: { width: '100%', maxWidth: 1180, alignSelf: 'center', paddingVertical: 70 }, resultsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 24 }, sectionKicker: { color: '#8489C3', fontSize: 13, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' }, sectionTitle: { color: '#020E56', fontSize: 30, lineHeight: 38, fontWeight: '800', marginTop: 7 }, resultCount: { color: '#667085', fontSize: 14 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 18 }, card: { backgroundColor: '#FFF', borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#E5E7EB', flexGrow: 1, flexBasis: '31%' as any, minWidth: 260, maxWidth: 380 }, thumbnail: { width: '100%', height: 190, backgroundColor: '#E9EBF5' }, cardBody: { padding: 18 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 }, cardTitle: { color: '#111827', fontSize: 17, fontWeight: '800', flex: 1 }, score: { color: '#0E156A', fontSize: 14, fontWeight: '800', backgroundColor: '#EFF0FA', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 7 }, cardMeta: { color: '#667085', fontSize: 13, marginTop: 8 }, cardTime: { color: '#020E56', fontSize: 16, fontWeight: '800', marginTop: 18 }, cardTimeLabel: { color: '#98A2B3', fontSize: 12, fontWeight: '500' }, emptyState: { backgroundColor: '#FFF', borderRadius: 16, padding: 28, borderWidth: 1, borderColor: '#E5E7EB' }, emptyCopy: { color: '#667085', fontSize: 15 }, tryAgain: { color: '#0E156A', fontSize: 14, fontWeight: '800', marginTop: 14 }, footer: { width: '100%', maxWidth: 1180, alignSelf: 'center', borderTopWidth: 1, borderTopColor: '#E5E7EB', paddingVertical: 24, flexDirection: 'row', justifyContent: 'space-between', gap: 18 }, footerText: { color: '#98A2B3', fontSize: 12 },
  '@media (max-width: 800px)': { page: { paddingHorizontal: 20 }, header: { height: 82 }, links: { display: 'none' }, hero: { minHeight: 610 }, title: { fontSize: 44, lineHeight: 48 }, subtitle: { fontSize: 16 }, character: { opacity: 0.22, width: 120 }, characterImage: { transform: [{ scale: 0.8 }] }, resultsSection: { paddingVertical: 48 }, resultsHeader: { alignItems: 'flex-start', flexDirection: 'column', gap: 12 }, sectionTitle: { fontSize: 25, lineHeight: 31 }, footer: { flexWrap: 'wrap' } },
  '@media (max-width: 430px)': { logo: { width: 132, height: 60 }, hero: { minHeight: 570 }, uploader: { minHeight: 205 }, title: { fontSize: 40, lineHeight: 43 }, footer: { flexDirection: 'column', gap: 8 } }
} as any);
